FROM 		alpine
LABEL maintainer "Stefan Stranger <stefan@stranger.nl>"
LABEL Description="This is a simple docker file for educational purpose. It print `Hello world!!' on console"
CMD echo "Dockerfile: Hello world !!"